In [5]:
!nvidia-smi

/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Fri Dec  8 15:59:38 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.103                Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
|  0%   36C    P8              13W / 450W |   1056MiB / 24564MiB |      0%      Default |
|                                         |                      |                  

In [65]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
print(torch.__version__)

2.1.1


# Tensors
creating tensors
- created using ``` torch.tensor() ```

In [8]:
# scalar
scalar = torch.tensor(7)

In [9]:
scalar.item()
# get back as python int

7

In [10]:
vector = torch.tensor([5, 6])

In [11]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])

In [12]:
MATRIX[0][0]

tensor(7)

In [13]:
TENSOR = torch.tensor([
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]],
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
])

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0][0]

tensor([1, 2, 3])

In [16]:
TENSOR[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random tensors
Random tensors are important because the way most neural networks learn is that they start with random tensors and adjust those random numbers to better represent the data


In [17]:
A = torch.randn(2, 3, 4)

In [18]:
A.shape

torch.Size([2, 3, 4])

In [19]:
A

tensor([[[-0.2356, -1.8742, -0.6586,  0.6785],
         [ 0.3185,  0.1526,  0.3080, -1.4691],
         [-0.8712,  0.2240, -0.1344, -0.4710]],

        [[-0.6339,  1.0456, -0.7557,  0.8077],
         [-2.3523,  0.3401,  1.1984, -0.8177],
         [-1.4484, -0.6700, -0.2048,  1.8236]]])

In [20]:
# Create a random tensor with similar shape to an image tensor
img = torch.rand((256, 256, 3))

In [21]:
img

tensor([[[0.6384, 0.1428, 0.5047],
         [0.2940, 0.5370, 0.7124],
         [0.1143, 0.9660, 0.6843],
         ...,
         [0.0131, 0.3357, 0.6430],
         [0.8676, 0.9927, 0.0263],
         [0.7696, 0.9062, 0.4705]],

        [[0.9132, 0.2499, 0.4237],
         [0.2558, 0.1772, 0.3455],
         [0.3178, 0.7726, 0.0508],
         ...,
         [0.5018, 0.0298, 0.8699],
         [0.0594, 0.1882, 0.4569],
         [0.8054, 0.6602, 0.3730]],

        [[0.2432, 0.9816, 0.1743],
         [0.5192, 0.1127, 0.3186],
         [0.7211, 0.1884, 0.8197],
         ...,
         [0.3885, 0.6365, 0.6960],
         [0.1982, 0.2242, 0.2598],
         [0.5055, 0.9194, 0.1553]],

        ...,

        [[0.3356, 0.7274, 0.9796],
         [0.8014, 0.5585, 0.1346],
         [0.2798, 0.3320, 0.6344],
         ...,
         [0.7341, 0.8358, 0.3691],
         [0.5729, 0.7363, 0.5606],
         [0.6498, 0.8636, 0.6740]],

        [[0.4627, 0.2695, 0.0398],
         [0.7429, 0.0494, 0.1930],
         [0.

# Zeros and ones
- Used to zero numbers out in matrix multiplications

In [22]:
zeros = torch.zeros((3, 4))

In [23]:
ones = torch.ones(3, 4)

# Arange
- Includes start but excludes stop

In [24]:
torch.arange(0, 12, 3)

tensor([0, 3, 6, 9])

In [25]:
# Create zero tensor with same dim as another tensor
zeros_like = torch.zeros_like(ones)

In [26]:
zeros_like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Tensor Attributes
- Default datatype: Float32 -> tensors we perform computations with must be of same dtype
    - check using ```torch.dtype```
- Device: cpu or gpu etc. -> tensors must be on same device
     - check using ```torch.device```
- requires_grad: track with computation graph
    - check using ```torch.requires_grad```

In [27]:
a = torch.randn(3, 4)

In [28]:
a.requires_grad

False

## Functions
-```type(new_data_type)``` returns new tensor with specified dtype (not in place)

In [29]:
b = a.type(torch.float16)

In [30]:
print(a.dtype, b.dtype)

torch.float32 torch.float16


# Tensor Manipulation
- Addition
- Subtraction
- Multiplication
- Division
- Matmul

In [31]:
a = torch.arange(0, 10, 2)

In [32]:
# Element wise multiplication
a * 2

tensor([ 0,  4,  8, 12, 16])

In [33]:
# Element wise addition
a * 3

tensor([ 0,  6, 12, 18, 24])

# Matrix Multiplication

In [34]:
# Element wise multiplication
a * a

tensor([ 0,  4, 16, 36, 64])

In [35]:
# Matmul
a @ a

tensor(120)

In [36]:
b = torch.zeros(2, 3, 4)
c = torch.randn(2, 4 , 6)

In [37]:
(b @ c).shape

torch.Size([2, 3, 6])

In [38]:
b @ c

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [39]:
a = torch.ones(3, 2, 2)
a[:, 0, 0] = 2

In [40]:
a

tensor([[[2., 1.],
         [1., 1.]],

        [[2., 1.],
         [1., 1.]],

        [[2., 1.],
         [1., 1.]]])

In [41]:
a.mean(0)

tensor([[2., 1.],
        [1., 1.]])

# Naming tensors
- To keep track of tensor dims without using indices, we can name them by passing in an extra parameter (list of strings)
- Use the `rename()` method to rename tensor dims
- The method `align_as()` returns a tensor with missing dimensions
added and existing ones permuted to the right order

In [42]:
a = torch.rand(3, 2, 2, names=["one", "two", "three"])

/tmp/ipykernel_6489/1540385880.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449201450/work/c10/core/TensorImpl.h:1900.)
  a = torch.rand(3, 2, 2, names=["one", "two", "three"])


In [43]:
b = a.rename(one="Channels", two="Rows", three="Cols") # MUST ASSIGN NEW VARIABLE NAME WHEN RENAMING
b

tensor([[[0.0863, 0.5108],
         [0.6280, 0.3610]],

        [[0.3513, 0.3544],
         [0.6538, 0.3036]],

        [[0.6539, 0.0934],
         [0.8714, 0.0401]]], names=('Channels', 'Rows', 'Cols'))

In [44]:
a

tensor([[[0.0863, 0.5108],
         [0.6280, 0.3610]],

        [[0.3513, 0.3544],
         [0.6538, 0.3036]],

        [[0.6539, 0.0934],
         [0.8714, 0.0401]]], names=('one', 'two', 'three'))

In [45]:
c = torch.zeros(2, 3, 2, names=("one", "two", "three")).align_as(a)

In [46]:
c

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]], names=('one', 'two', 'three'))

# Torch Dtypes
- If we pass a list of ints to `torch.tensor`, torch automatically creates an int64 tensor
- convert via the `.to()` method
- When performing computations, torch automatically converts all tensors to the highest precision-> if we want a computation resulting in a float32 tensor, all the components should be at most int32

In [47]:
double_points = torch.zeros(10, 2).to(torch.double)
double_points.dtype

torch.float64

# The tensor API
- Most operations on & between tensors are available in the torch module & can be called as methods
    - `torch.transpose(a, 0, 1)` or `a.transpose(0, 1)`
# Tensor storage
- managed by `torch.Storage` instances: 1-d array of numerical data (continuous block of memory containing numbers of the same dtype)
- torch `Tensor` instances  can index into storage using an offset & per-dimension strides   
- Multiple `Tensor` instances can index the same storage simultaneously (with different dimensionality)
- Can index into the storage (Always 1 D) directly to change value of tensor
## Size, Offset & Stride
- A tensor stores the size, offset & stride in a tuple in order to index into storage correctly
- **Offset**: Where to begin in the 1D array in memory ( Usually 0 unless tensor is a view of a larger tensor)
- **Size**: Tuple indicating how many elements across each dim the tensor represents (shape)
- **Stride**: Number of elements in storage that need to be skipped over to obtain the next element along each dim
    - e.g. stride along the rows is the number of elements you need to move in memory to go from one element in a row to the next element in the same row 
- Makes operations such as transposing & extracting sub-tensors more efficient (avoids allocation of new memory) `second_point = points[1]` creates a tensor that indexes into the same storage-> **Potential Issue:** alterations to the sub-tensor will affect the main tensor-> May need to copy data over to a new tensor
- Solution: `second_point = points[1].clone()`

In [48]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [49]:
points.storage() # Data stored in continuous array even though tensor is 2d

/tmp/ipykernel_6489/1256144357.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage() # Data stored in continuous array even though tensor is 2d


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [50]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset() # Offset in storage between the first 2 elements

2

In [51]:
second_point, second_point.size()

(tensor([5., 3.]), torch.Size([2]))

In [52]:
points.stride() # Provides stride in (rows, cols) -> stride in cols is 1

(2, 1)

In [53]:
points.storage()[0], points.storage()[1] # As seen here, the first & second elements of the storage are the items in the first row-> stride between cols = 1

(4.0, 1.0)

In [54]:
points.storage()[2]

5.0

#### As seen above: Accessing an element `i, j` in a 2D tensor results in accessing the 
```storage_offset + stride[0] * i + stride[1] * j``` element in the storage. 

# In place operations
- Some in place operations exist as methods of the `Tensor` object: have trailing underscores in their names: `zero_()`
- **Any method without the underscore returns a new tensor & leaves the old one unchanged**

In [55]:
a

tensor([[[0.0863, 0.5108],
         [0.6280, 0.3610]],

        [[0.3513, 0.3544],
         [0.6538, 0.3036]],

        [[0.6539, 0.0934],
         [0.8714, 0.0401]]], names=('one', 'two', 'three'))

In [56]:
a.zero_()
a

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]], names=('one', 'two', 'three'))

# Transposing Tensors
- Changes the stride & shape without allocating new memory
- Can be done for n-D tensors where n > 2 too: Specify dims for transpose, e.g. `a.transpose(0, 2)` 
- Tensor whose values are laid out in storage starting from the rightmost dimension onwards is **continuous**-> Efficient because no need to jump around in storage
    - Check for continuity: `a.is_continuous()`
    - Can make non-continuous tensor continuous by allocating new storage: `a.continuous()` 

In [57]:
a = torch.arange(0, 12, 1).reshape(2, 2, 3)

In [58]:
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [59]:
a.transpose(0, 2), a.transpose(0, 2).shape # The 1st row of the 2nd dim is now the first col of the 0th dim

(tensor([[[ 0,  6],
          [ 3,  9]],
 
         [[ 1,  7],
          [ 4, 10]],
 
         [[ 2,  8],
          [ 5, 11]]]),
 torch.Size([3, 2, 2]))

# Torch & GPUs
- Tensors are stored on CPU by default but can be moved to GPU for parallel computations
- `device` is a var which tells us where the tensor is placed
    - create tensor on gpu: `points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')`
    - Copy a tensor to GPU: `points_gpu = points.to(device='cuda')` (Yields new tensor with same data but stored on RAM of GPU)
    - Shorthand method of the same thing `points_gpu = points.cuda()`
- GPU & CPU tensors share the same API -> Can run code regardless of where it is running
- After a tensor has been copied to the GPU, the CPU knows nothing about the computations we perform with it

In [60]:
a = torch.randn(3, 2)
a_gpu = a.cuda()
a_gpu_float = a.to(device='cuda', dtype=torch.float32)

In [61]:
a.device, a_gpu.device, a_gpu_float.device, a_gpu_float.dtype

(device(type='cpu'),
 device(type='cuda', index=0),
 device(type='cuda', index=0),
 torch.float32)

# NumPy interoperability
- Torch tensors on CPU can be converted to NumPy arrays efficiently (Zero-copy interoperability)
- `points.numpy()`-> Resulting array shares same underlying memory as the tensor
-  If the tensor is allocated on the GPU, PyTorch will make a copy of the content of the tensor into a NumPy array allocated on the CPU

# Serializing tensors
- Can use the `pickle` library to save tensors & load it back -> avoid retraining model
- `torch.save(points, file_path)` & `points = torch.load('../data/p1ch3/ourpoints.t')`
- OR 
- `with open('../data/p1ch3/ourpoints.t','wb') as f:
torch.save(points, f)`
- `with open('../data/p1ch3/ourpoints.t','rb') as f:
points = torch.load(f)`
- Only works with PyTorch, cannot read the tensor with anything else

# Exercises

In [71]:
a = torch.tensor(list(range(9)))
a.stride() # prediction: 1
a.size() # prediction: 9
a.shape # prediction: ,9

torch.Size([9])

In [73]:
b = a.view(3, 3) # Changes the shape of a to 3 x 3
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [74]:
a[-1] = 0

In [77]:
b, b.stride() # Changes to a affects b -> the tensors share the same storage


(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 0]]),
 (3, 1))

In [82]:
c = b[1: ,1:] # prediction of size: 2 x 2, offset: 1, stride: 3, 1 -> correction: Correct offset = 4 (STARTS IN THE SECOND ROW!!)
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

In [107]:
d = torch.randn(3, 3, dtype=torch.float64)

In [108]:
torch.cos(d), torch.sqrt(d) # element wise operations work!

(tensor([[ 0.1415,  0.9340,  0.2817],
         [ 0.2700,  0.9684,  0.2486],
         [ 0.4386, -0.0495,  0.6609]], dtype=torch.float64),
 tensor([[1.1954, 0.6045, 1.1337],
         [   nan, 0.5019,    nan],
         [   nan, 1.2729,    nan]], dtype=torch.float64))

In [109]:
torch.cos_(d), torch.sqrt_(d) # In- place operation only works on float64

(tensor([[0.3761, 0.9664, 0.5308],
         [0.5196, 0.9841, 0.4986],
         [0.6622,    nan, 0.8130]], dtype=torch.float64),
 tensor([[0.3761, 0.9664, 0.5308],
         [0.5196, 0.9841, 0.4986],
         [0.6622,    nan, 0.8130]], dtype=torch.float64))

In [110]:
d

tensor([[0.3761, 0.9664, 0.5308],
        [0.5196, 0.9841, 0.4986],
        [0.6622,    nan, 0.8130]], dtype=torch.float64)

In [111]:
e = torch.randn(3, 3)
e.to(dtype=torch.float64) # The .to method is not in-place

tensor([[ 0.7245, -0.1111,  1.2730],
        [-0.9719, -0.2573, -0.9584],
        [ 0.0668,  0.5899, -0.4257]], dtype=torch.float64)

In [112]:
e.dtype

torch.float32